version: "2.3"

services:
    xterm:
        build: .
        environment:
          DISPLAY: $DISPLAY
          UID: $UID
          GID: $GID
        user: "${UID}:${GID}"
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ~/.Xauthority:/root/.Xauthority
          - "/home:/home"
